[package]
name = "youtube_captions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8"
regex = "1"
css-color-parser = "0.1.2"
rgb = "0.8"
ansi_rgb = "0.2.0"